name: Continuous Deployment

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 15
      - run: npm ci
      - run: npm run build
      - run: git config --global user.email "tahmidrahman2812@outlook.com" && git config --global user.name "tahmid148" && npm run deploy
