name: Continuous Deployment

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 15
      - run: npm ci
      - run: npm run build
      - run: git config --global user.name $user_name
      - run: git config --global user.email $user_email
      - run: git remote set-url origin https://${github_token}@github.com/${repository}
      - run: npm run deploy
      - env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}