name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  test_push:
    runs_ons: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm ci
      - run: npm test
      - run: npm run build